#!/bin/bash
CONTAINERS="dockerbridge nginx docker-gen mongo_db postgres_db `docker ps | grep -E openease/hydro-knowrob-daemon\|openease/indigo-knowrob-daemon\|openease/kinetic-knowrob-daemon\|openease/knowrob\|openease/easeapp\|openease/login | awk '{print $1}'`"
docker stop -t 3 $CONTAINERS
if [ "$1" == "--rm" ]; then
	docker rm $CONTAINERS
fi
